<?php
/** @var $lista \Principal\Service\Principal[] */
?>
<div class="page-head">
    <br/><br/>
    <div class="container">
        <div align="center">
            <img src="/assets/img/logo/galo.png" max-width=" 280px" height="280px"/>
            <br/>

            <b><p style="font-size: 20px; color: #032a51"> Bem vindo ao Galinheiro!</p></b>
            <img src="/assets/img/logo/Logo-galo.png" max-width=237x" height="65px"/>


        </div>
    </div>
    <?php //echo $this->Auth()->nm_usuario; ?>
    <?php //echo $this->Auth()->id_usuario; ?>

</div>




