<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">

<div class="col-md-12">
    <div class="table-responsive">
        <table class="table table-striped" id="tablesorterSolicitacao">
            <thead>
            <tr>
                <th class="text-center">Registro</th>
                <th class="text-center">Unidade</th>
                <th class="text-center">Departamento</th>
                <th class="text-center">Solicitante</th>
                <th class="text-center">Status</th>
                <th class="text-center">Tramitação</th>
                <th class="text-center">Ações</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <th class="text-center">Registro</th>
                <th class="text-center">Unidade</th>
                <th class="text-center">Departamento</th>
                <th class="text-center">Solicitante</th>
                <th class="text-center">Status</th>
                <th class="text-center">Tramitação</th>
                <th class="text-center">Ações</th>
            </tr>
            <tr>
                <th colspan="7" class="ts-pager form-horizontal">
                    <?php
                    echo $this->paginationControl(
                        $paginator, 'Sliding', 'partials/pagination.phtml', [
                            'urlPagination' => '/solicitacao-solicitacao/index-pagination',
                            'countPerPage' => $countPerPage,
                            'divData' => '#solicitacao-pagination',
                        ]
                    );
                    ?>
                </th>
            </tr>
            </tfoot>
            <?php
            $numeroLinha = (($paginator->getCurrentPageNumber() - 1) * $paginator->getItemCountPerPage());
            if (!empty($paginator)) {
                ?>
                <tbody class="">
                <tr role="row" class="tablesorter-filter-row">
                    <?php
                    foreach ($camposFilter as $key => $campoFilter) {
                        ?>
                        <td>
                            <?php
                            if (!is_null($campoFilter)) {
                                ?>
                                <input type="search" placeholder="" class="tablesorter-filter" data-column="<?= $key ?>"
                                       value="<?= isset($filter[$key]) ? $filter[$key] : '' ?>">
                                <?php
                            } else {
                                ?>
                                &nbsp;
                                <?php
                            }
                            ?>
                        </td>
                        <?php
                    }
                    ?>
                </tr>
                <?php
                foreach ($paginator as $key => $solicitacao) {
                    ?>
                    <tr>
                        <td class="text-center"><?= $solicitacao['id_solicitacao'] ?></td>
                        <td class="text-center"><?= \Estrutura\Helpers\String::nomeMaiusculo($solicitacao['nm_unidade']) ?></td>
                        <td class="text-center"><?= \Estrutura\Helpers\String::nomeMaiusculo($solicitacao['nm_departamento']) ?></td>
                        <td class="text-center"><?= \Estrutura\Helpers\String::nomeMaiusculo($solicitacao['nm_solicitante']) ?></td>
                        <td class="text-center">
                            <?php
                            if ($solicitacao['nm_status'] == 'Em Produção') { ?>
                                <span class='label label-default'>Em Produção</span>
                                <?php
                            } elseif ($solicitacao['nm_status'] == 'Em Aprovação') { ?>
                                <span class='label label-default'>Em Aprovação</span>
                                <?php
                            } elseif ($solicitacao['nm_status'] == 'Aprovado') { ?>
                                <span class='label label-info'>Aprovado</span>
                                <?php
                            } elseif ($solicitacao['nm_status'] == 'Concluído') { ?>
                                <span class='label label-success'>Concluído</span>
                                <?php
                            } elseif ($solicitacao['nm_status'] == 'Atrasado') { ?>
                                <span class='label label-danger'>Atrasado</span>
                                <?php
                            } elseif ($solicitacao['nm_status'] == 'Cancelado') { ?>
                                <span class='label label-danger'>Cancelado</span>
                                <?php
                            } elseif ($solicitacao['nm_status'] == 'Retornado Para Ajustes') { ?>
                                <span class='label label-danger'>Retornado Para Ajustes</span>
                                <?php
                            } elseif ($solicitacao['nm_status'] == 'Nova Demanda') { ?>
                                <span class='label label-warning'>Nova Demanda</span>
                                <?php
                            } elseif ($solicitacao['nm_status'] == 'No Planejamento') { ?>
                                <span class='label label-primary'>No Planejamento</span>
                                <?php
                            } elseif ($solicitacao['nm_status'] == 'Em Execução') { ?>
                                <span class='label label-success'>Em Execução</span>
                                <?php
                            } elseif ($solicitacao['nm_status'] == 'Retornado Para Ajustes') { ?>
                                <span class='label label-warning'>Retornado Para Ajustes</span>
                                <?php
                            }
                            ?>
                        </td>
                        <td class="text-center">
                            <span class="btn-group" style="width: 250px;">
                            <?php
                            if ($solicitacao['nm_status'] == 'I' || $solicitacao['nm_status'] == 'R') { ?>
                                <?= \Estrutura\Service\HtmlHelper::botaoAcao(
                                    $this->url('navegacao', array('controller' => $controller, 'action' => 'enviar-para-validacao', 'id' => Estrutura\Helpers\Cript::enc($solicitacao['id_plano_mudanca']))),
                                    'Enviar para Validação',
                                    'enviar_para_validacao',
                                    'glyphicon glyphicon-share-alt',
                                    'btn-alterar btn-xs btn-alterar-customizado'
                                ) ?>
                                <?php
                            } elseif ($solicitacao['nm_status'] == 'G') { ?>
                                <?= \Estrutura\Service\HtmlHelper::botaoAcao(
                                    $this->url('navegacao', array('controller' => $controller, 'action' => 'enviar-para-cancelamento', 'id' => Estrutura\Helpers\Cript::enc($solicitacao['id_solicitacao']))),
                                    'Cancelar Plano de Mudança',
                                    'cancelar_plano_mudanca',
                                    'glyphicon glyphicon-fire',
                                    'btn-alterar btn-xs btn-alterar-customizado'
                                ) ?>

                                <?= \Estrutura\Service\HtmlHelper::botaoAcao(
                                    $this->url('navegacao', array('controller' => $controller, 'action' => 'devolver-para-ajustes', 'id' => Estrutura\Helpers\Cript::enc($solicitacao['id_solicitacao']))),
                                    'Solicitar Adequações',
                                    'devolver_para_adequacao_avaliador',
                                    'glyphicon glyphicon-wrench',
                                    'btn-alterar btn-xs btn-alterar-customizado'
                                ) ?>

                                <?= \Estrutura\Service\HtmlHelper::botaoAcao(
                                    $this->url('navegacao', array('controller' => $controller, 'action' => 'aprovar-plano-sem-gerar-ordem-servico', 'id' => Estrutura\Helpers\Cript::enc($solicitacao['id_solicitacao']))),
                                    'Aprovar plano de mudança (Não gera ordem de serviço)',
                                    'aprovar_plano_mudanca',
                                    'glyphicon glyphicon-send',
                                    'btn-alterar btn-xs btn-alterar-customizado'
                                ) ?>

                                <?= \Estrutura\Service\HtmlHelper::botaoAcao(
                                    $this->url('navegacao', array('controller' => $controller, 'action' => 'aprovar-plano-mudanca', 'id' => Estrutura\Helpers\Cript::enc($solicitacao['id_solicitacao']))),
                                    'Aprovar e gerar ordem de serviço',
                                    'aprovar_plano_mudanca',
                                    'glyphicon glyphicon-usd',
                                    'btn-alterar btn-xs btn-alterar-customizado'
                                ) ?>

                                <?php
                            } elseif ($solicitacao['nm_status'] == 'Cancelado') { ?>
                                <span title='Plano de Mudança Aprovado' class='label label-danger'>Cancelado</span>
                                <!-- Quando a mudança for aprovada, Ninguem mais poderá alterar seu conteúdo-->
                                <?php
                            } elseif ($solicitacao['nm_status'] == 'Concluído') { ?>
                                <span title='Plano de Mudança Concluído' class='label label-success'>Concluído</span>
                                <?php
                            } elseif ($solicitacao['nm_status'] == 'Em Aprovação') { ?>
                                <?= \Estrutura\Service\HtmlHelper::botaoAcao(
                                    $this->url('navegacao', array('controller' => $controller, 'action' => 'enviar-para-cancelamento', 'id' => Estrutura\Helpers\Cript::enc($solicitacao['id_solicitacao']))),
                                    'Cancelar Solicitação',
                                    'cancelar_solicitacao',
                                    'glyphicon glyphicon-fire',
                                    'btn-alterar btn-xs btn-alterar-customizado'
                                ) ?>

                                <?= \Estrutura\Service\HtmlHelper::botaoAcao(
                                    $this->url('navegacao', array('controller' => $controller, 'action' => 'enviar-para-aprovacao', 'id' => Estrutura\Helpers\Cript::enc($solicitacao['id_solicitacao']))),
                                    'Ativar Solicitação e Enviar para Aprovação',
                                    'enviar_para_aprovacao',
                                    'glyphicon glyphicon-ok-sign',
                                    'btn-alterar btn-xs btn-alterar-customizado'
                                ) ?>
                                <?php
                            } elseif ($solicitacao['nm_status'] == 'N') { ?>
                                <span title='Plano de Mudança Não Aprovada'
                                      class='label label-danger'>Não Aprovada</span>
                                <?php
                            } elseif ($solicitacao['nm_status'] == 'No Planejamento') { ?>
                                <?= \Estrutura\Service\HtmlHelper::botaoAcao(
                                    $this->url('navegacao', array('controller' => $controller, 'action' => 'devolver-para-correcao', 'id' => Estrutura\Helpers\Cript::enc($solicitacao['id_solicitacao']))),
                                    'Devolver para Correções',
                                    'devolver_para_correcoes',
                                    'glyphicon glyphicon-thumbs-down',
                                    'btn-alterar btn-xs btn-alterar-customizado'
                                ) ?>

                                <?= \Estrutura\Service\HtmlHelper::botaoAcao(
                                    $this->url('navegacao', array('controller' => $controller, 'action' => 'enviar-para-aprovacao', 'id' => Estrutura\Helpers\Cript::enc($solicitacao['id_solicitacao']))),
                                    'Enviar para Aprovação',
                                    'enviar_para_aprovacao',
                                    'glyphicon glyphicon-ok-sign',
                                    'btn-alterar btn-xs btn-alterar-customizado'
                                ) ?>
                                <?php
                            } elseif ($solicitacao['nm_status'] == 'Retornado Para Ajustes') { ?>
                                <?= \Estrutura\Service\HtmlHelper::botaoAcao(
                                    $this->url('navegacao', array('controller' => $controller, 'action' => 'devolver-para-correcao', 'id' => Estrutura\Helpers\Cript::enc($solicitacao['id_solicitacao']))),
                                    'Devolver para Correções',
                                    'devolver_para_correcoes',
                                    'glyphicon glyphicon-thumbs-down',
                                    'btn-alterar btn-xs btn-alterar-customizado'
                                ) ?>
                                <?php
                            }
                            ?>
                            </span>
                        </td>

                        <td class="text-center">
                                <span class="btn-group" style="width: 150px;">
                                    <?= \Estrutura\Service\HtmlHelper::botaoAlterar($this->url('navegacao', array('controller' => $controller, 'action' => 'cadastro', 'id' => Estrutura\Helpers\Cript::enc($solicitacao['id_solicitacao']))), 'Modificar Solicitação') ?>
                                    <?= \Estrutura\Service\HtmlHelper::botaoExcluir($this->url('navegacao', array('controller' => $controller, 'action' => 'excluir', 'id' => Estrutura\Helpers\Cript::enc($solicitacao['id_solicitacao'])))) ?>
                                </span>
                        </td>
                    </tr>
                    <?php
                }
                ?>
                </tbody>
                <?php
            }
            ?>

        </table>
        <div class="row">
            <div class="col-md-12">
                <a href="<?= $this->url('navegacao', ['controller' => 'principal-principal']) ?>"
                   class="btn btn-primary" title="Retorna para a Página Principal">Início</a>
            </div>
        </div>
    </div>
</div>
<script
    src="/assets/compact-js/moment.js,validator.min.js,jquery.mask.min.js,jquery.ui.widget.js,jquery.tablesorter.js,jquery.tablesorter.widgets.js,jquery.tablesorter.pager.js"
    type="text/javascript">

</script>
<script type="text/javascript" language="javascript">
    $(function () {

        // NOTE: $.tablesorter.theme.bootstrap is ALREADY INCLUDED in the jquery.tablesorter.widgets.js
        // file; it is included here to show how you can modify the default classes
        $.tablesorter.themes.bootstrap = {
            // these classes are added to the table. To see other table classes available,
            // look here: http://getbootstrap.com/css/#tables
            table: 'table table-bordered',
            caption: 'caption',
            header: 'bootstrap-header', // give the header a gradient background
            footerRow: '',
            footerCells: '',
            icons: '', // add "icon-white" to make them white; this icon class is added to the <i> in the header
            sortNone: 'bootstrap-icon-unsorted',
            sortAsc: 'icon-chevron-up glyphicon glyphicon-chevron-up', // includes classes for Bootstrap v2 & v3
            sortDesc: 'icon-chevron-down glyphicon glyphicon-chevron-down', // includes classes for Bootstrap v2 & v3
            active: '', // applied when column is sorted
            hover: '', // use custom css here - bootstrap class may not override it
            filterRow: '', // filter row class
            even: '', // odd row zebra striping
            odd: ''  // even row zebra striping
        };

        // call the tablesorter plugin and apply the uitheme widget
        $("#tablesorterSolicitacao").tablesorter({
            // this will apply the bootstrap theme if "uitheme" widget is included
            // the widgetOptions.uitheme is no longer required to be set
            theme: "bootstrap",
            widthFixed: true,
            headerTemplate: '{content} {icon}', // new in v2.7. Needed to add the bootstrap icon!

            // widget code contained in the jquery.tablesorter.widgets.js file
            // use the zebra stripe widget if you plan on hiding any rows (filter widget)
            widgets: ["uitheme", "zebra"],
            widgetOptions: {
                // using the default zebra striping class name, so it actually isn't included in the theme variable above
                // this is ONLY needed for bootstrap theming if you are using the filter widget, because rows are hidden
                zebra: ["even", "odd"],
                // reset filters button
                filter_reset: ".reset"

                // set the uitheme widget to use the bootstrap theme class names
                // this is no longer required, if theme is set
                // ,uitheme : "bootstrap"

            },
            headers: {
                5: {sorter: false}
            }
        });
    });
</script>
