<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">

<div class="page-head">
    <h2>Lista de Solicitações</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?= $this->url('navegacao', array('controller' => $controller, 'action' => 'cadastro')) ?>" title="Adicionar nova solicitação">Nova Solicitação</a>
        </div>
    </div>
    <br />
    <div class="row" id="solicitacao-pagination"></div>
</div>

<script>
    $(function () {

        $.ajax({
            type: "post",
            dataType: "text",
            cache: false,
            url: '/solicitacao-solicitacao/index-pagination',
            async: true,
            data: {
            },
            beforeSend: function () {

                $('#solicitacao-pagination').html(
                    '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                );
            },
            success: function (data) {

                $('#solicitacao-pagination').html(data);
            }
        });

    })
</script>
